/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EccWrapper */

#ifndef _Included_EccWrapper
#define _Included_EccWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EccWrapper
 * Method:    generateKeyPair
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EccWrapper_generateKeyPair
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
