/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ecc_ecc_EccWrapper */

#ifndef _Included_com_ecc_ecc_EccWrapper
#define _Included_com_ecc_ecc_EccWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ecc_ecc_EccWrapper
 * Method:    generateKeyPair
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ecc_ecc_EccWrapper_generateKeyPair
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
